language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-16

before_script:
    - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
